### ISSUE TITLE
Tries to load other .yml files

### ISSUE THREAD

**Issue by callym** [aronim/serverless-plugin-colocate#1]
Using this plugin tries to load my `.gitlab-ci.yml` file from the root of my product, which breaks a lot of things.
I can add `ignore: true` to the start of that file, but ideally it'd not try and load this file to begin with.

**Comment by kevinsewell** [comment]
Agreed. I guess some default criteria for filtering YAML files would be...

- excluding "hidden" files (ie. starting with ".")
- only including YAML files that have **functions** and **resources** as root elements

And then perhaps also adding explicit excludes filters via custom element?

Do you think that should be sufficient for the moment?

**Comment by callym** [comment]
Yeah I think that would be a great solution 😄

**Comment by kevinsewell** [comment]
Apologies that took so long. I eventually implemented the solution using Globby. The default configuration includes `["**/*.yml", "**/*.yaml"]` and excludes `["node_modules/**", "serverless.yml"]`. With the ability to either override these defaults, as well as, adding additional excludes via the 

```yml
custom:
  colocate:
    defaultInclude:         # Optional: For very edge cases where these includes don't meet your needs
      - "**/*.yml"
      - "**/*.yaml"
    defaultExclude:         # Optional: For very edge cases where these includes don't meet your needs
      - "serverless.yml"
      - "node_modules/**"
    exclude:                # Optional: Exclude additional patterns from fragment search
      - "**/goodbye.yml"
```
 
I hope that makes things a little neater on your side.
